### ISSUE TITLE
It throws when a select value contains for example '-'

### ISSUE THREAD

**Issue by Skywalker13** [messageformat/messageformat#227]
Hello

Code:
```js
'use strict';

const MessageFormat = require('messageformat');
const mf = new MessageFormat('fr');
const selectMessage = mf.compile(
  `{
    periodicity, select,
    once {coût unique}
    weekly {coût hebdomadaire}
    monthly {coût mensuel}
    quarterly {coût trimestriel}
    half-yearly {coût semestriel}
    annually {coût annuel}
    other {{periodicity}}
  }`
);

console.log(selectMessage({periodicity: 'weekly'}));
console.log(selectMessage({periodicity: 'half-yearly'}));
console.log(selectMessage({}));
```

Result:
```
node_modules/messageformat-parser/parser.js:1605
    throw peg$buildStructuredError(
    ^
SyntaxError: Expected "{", [\t-\r \x85  ], or [^\t-\r \x85  !-/:-@[-\^`{-~¡-§©«¬®°±¶»¿×÷‐-‧‰-‾⁁-⁓⁕-⁞←-⑟─-❵➔-⯿⸀-⹿、-〃〈-〠〰﴾﴿﹅﹆] but "-" found.
    at peg$buildStructuredError (node_modules/messageformat-parser/parser.js:368:12)
    at peg$parse (node_modules/messageformat-parser/parser.js:1605:11)
    at Compiler.compile (node_modules/messageformat/lib/compiler.js:157:13)
    at MessageFormat.compile (node_modules/messageformat/lib/messageformat.js:339:22)
    at Object.<anonymous> (test.js:5:26)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

With this online service: https://format-message.github.io/icu-message-format-for-translators/editor.html
It works perfectly
![image](https://user-images.githubusercontent.com/397862/53553838-d0e21780-3b3e-11e9-8973-965674ccee6a.png)

Regards

**Comment by eemeli** [comment]
This is the same issue as in #195, and it's caused by our closer conformance with the spec, which prohibits the `-` character from select category names. For a fix, could you e.g. replace `half-yearly` with `half_yearly`?

**Comment by Skywalker13** [comment]
:-(

Thank you

With an hack.. because it's a value stored in documents (databases). Then I must use a `replace(/-/g, '_')` on `periodicity` but it's a bit ugly. Maybe It's better if I don't use ICU here and I keep a `switch case`.
