### ISSUE TITLE
Parser fails when custom formatter name contains other formatter name

### ISSUE THREAD

**Issue by orange-buffalo** [messageformat/messageformat#274]
Consider the following case of a custom formatter:
```javascript
const messageFormat = new MessageFormat(locale);
messageFormat.addFormatters({
  datetime: // custom formatter function,
});
const formatter = messageFormat.compile('{0, datetime, medium}', locale);
```
It is expected to work, i.e. that `formatter` gets a compiled function assigned. But instead an exception is thrown:
```
{
  "message": "Expected \",\" or \"}\" but \"t\" found.",
  "expected": [
    {
      "type": "literal",
      "text": ",",
      "ignoreCase": false
    },
    {
      "type": "literal",
      "text": ",",
      "ignoreCase": false
    },
    {
      "type": "literal",
      "text": "}",
      "ignoreCase": false
    }
  ],
  "found": "t",
  "location": {
    "start": {
      "offset": 8,
      "line": 1,
      "column": 9
    },
    "end": {
      "offset": 9,
      "line": 1,
      "column": 10
    }
  },
  "name": "SyntaxError"
}
```
with stack (version 2.3.0, included via `npm`):
```
"SyntaxError: Expected "," or "}" but "t" found.
    at Xt (webpack-internal:///./node_modules/messageformat/messageformat.js:1:25209)
    at parse (webpack-internal:///./node_modules/messageformat/messageformat.js:1:33364)
    at t.value (webpack-internal:///./node_modules/messageformat/messageformat.js:1:41241)
    at t.value (webpack-internal:///./node_modules/messageformat/messageformat.js:1:48429)
    ...
```

It seems that the cause is existing `date` formatter - renaming `datetime` to anything else that does not start with `date` resolves the issue. 

Is it possible to support this case?

**Comment by eemeli** [comment]
Testing would indicate that at least with the current version this is fixed:

```js
const mf = new MessageFormat('en', { customFormatters: { datetime: (v) => `dt <${v}>` } })
const msg = mf.compile('{0, datetime, medium}')
msg(['foo'])
// 'dt <foo>'
```

**Comment by orange-buffalo** [comment]
Awesome, thanks!
