### ISSUE TITLE
Complex date format cannot be compiled

### ISSUE THREAD

**Issue by princescar** [messageformat/messageformat#435]
When compiling message like `Started from {startTime, date, ::'MMM d, H:m'}`, we will get an error:

```
/Users/halbert/Developer/messageformat/node_modules/.pnpm/@messageformat+core@3.4.0/node_modules/@messageformat/core/lib/compiler.js:182
            onError(new DateFormatError(msg, token, DateFormatError.WARNING));
                    ^

DateFormatError: Ignoring string part: MMM d, H:m
    at getDateFormatOptions (/Users/halbert/Developer/messageformat/node_modules/.pnpm/@messageformat+core@3.4.0/node_modules/@messageformat/core/lib/compiler.js:182:21)
    at getDateFormatter (/Users/halbert/Developer/messageformat/node_modules/.pnpm/@messageformat+core@3.4.0/node_modules/@messageformat/core/lib/compiler.js:360:17)
    at Compiler.setDateFormatter (/Users/halbert/Developer/messageformat/node_modules/.pnpm/@messageformat+core@3.4.0/node_modules/@messageformat/core/lib/compiler.js:2136:29)
    at Compiler.token (/Users/halbert/Developer/messageformat/node_modules/.pnpm/@messageformat+core@3.4.0/node_modules/@messageformat/core/lib/compiler.js:1967:35)
    at /Users/halbert/Developer/messageformat/node_modules/.pnpm/@messageformat+core@3.4.0/node_modules/@messageformat/core/lib/compiler.js:1889:70
    at Array.map (<anonymous>)
    at Compiler.compile (/Users/halbert/Developer/messageformat/node_modules/.pnpm/@messageformat+core@3.4.0/node_modules/@messageformat/core/lib/compiler.js:1889:52)
    at Compiler.compile (/Users/halbert/Developer/messageformat/node_modules/.pnpm/@messageformat+core@3.4.0/node_modules/@messageformat/core/lib/compiler.js:1877:36)
    at Compiler.compile (/Users/halbert/Developer/messageformat/node_modules/.pnpm/@messageformat+core@3.4.0/node_modules/@messageformat/core/lib/compiler.js:1877:36)
    at compileModule (/Users/halbert/Developer/messageformat/node_modules/.pnpm/@messageformat+core@3.4.0/node_modules/@messageformat/core/lib/compile-module.js:45:29) {
  token: { char: "'", str: 'MMM d, H:m', width: 12 },
  type: 'error'
}
```

Currently a workaround would be `Started from {startTime, date, ::MMM} {startTime, date, ::d}, {startTime, date, ::H}:{startTime, date, ::m}`, but that's ugly.

**Comment by princescar** [comment]
The format should be `::MMMdHm`
